---
name: Terraform CI/CD

on:
  push:
    branches:
      - main # Adjust the branch as needed

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      TF_LOG: INFO # Optional: Enable detailed Terraform logs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Specify the desired Terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref_name == 'main'
        run: terraform apply -var="core_count=1" -var="thread_count=1" -auto-approve tfplan

      - name: Terraform Destroy
        if: github.ref_name == 'main'
        run: terraform destroy -var="core_count=1" -var="thread_count=1" -auto-approve
